config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  devise_scope :user do
    get '/auth/google_oauth2/callback', to: 'sessions#google_auth'
  end
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :documents do
    member do
      get :export
      get :generate_pdf
    end
  end
  resources :subscriptions, only: %i[index update] do
    collection do
      get :plans
    end
  end
  resources :payments, only: :index
end

app/models/document.rb
# frozen_string_literal: true

class Document < ApplicationRecord
  # Association
  belongs_to :user
end

app/controllers/documents_controller.rb
# frozen_string_literal: true

# Controller to perform Document CRUD
# rubocop:disable Metrics/ClassLength
class DocumentsController < ApplicationController
  require 'json'
  require 'open-uri'
  before_action :set_document, only: %i[show edit update destroy export generate_pdf]

  def index
    @documents = current_user.documents
  end

  def show; end

  # rubocop:disable Metrics/Metrics/MethodLength
  # rubocop:disable Metrics/AbcSize
  def new
    access_token_response = execute_access_token_request
    unless access_token_response.code == '200'
      return redirect_to documents_url,
                         notice: I18n.t('EForm.Messages.Error.WentWrong')
    end

    access_token_data = JSON.parse(access_token_response.body)
    interview_response = execute_interview_request(access_token_data)
    unless interview_response.code == '201'
      return redirect_to documents_url,
                         notice: I18n.t('EForm.Messages.Error.WentWrong')
    end

    interview_data = JSON.parse(interview_response.body)
    @interview_id = interview_data['interviewId']
    @service_token = interview_response.each_header.to_h['rl-rdoc-servicetoken']
  end
  # rubocop:enable Metrics/Metrics/MethodLength
  # rubocop:enable Metrics/AbcSize

  def edit; end

  def create
    @document = Document.new(document_params)
    @document.user_id = current_user.id

    if @document.save
      redirect_to documents_url, notice: I18n.t('EForm.Messages.Success.Created')
    else
      redirect_to documents_url
    end
  end

  def update
    return unless @document.update(document_params)
    return render json: { status: 200, message: I18n.t('EForm.Messages.Success.Updated') } if request.xhr?

    redirect_to documents_path, notice: I18n.t('EForm.Messages.Success.Updated')
  end

  def destroy
    @document.destroy

    redirect_to documents_url, notice: I18n.t('EForm.Messages.Success.Deleted')
  end

  def export
    return unless params[:from].present?

    email_me_the_document(@document) if params[:from] == 'email'
    redirect_to generate_pdf_document_path(pdf_params) if params[:from] == 'download' || params[:from] == 'print'
  end

  def generate_pdf
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: (DateTime.now + @document.id).to_s
      end
    end
  end

  def execute_access_token_request
    make_request(ENV['ACCESS_TOKEN_URL'], request_header, access_request_body)
  end

  def execute_interview_request(response)
    headers = request_header.merge({ 'Authorization' => "Bearer #{response['access_token']}" })
    make_request(ENV['INTERVIEW_URL'], headers, interview_request_body)
  end

  def request_header
    {
      'Content-Type' => 'application/json',
      'Accept' => 'application/json'
    }
  end

  def make_request(uri, headers = {}, body = nil, type = 'Post')
    uri = URI.parse(uri.to_s)
    request = "Net::HTTP::#{type}".constantize.new(uri)
    headers.each_with_object(request) do |(k, v), req|
      req[k] = v
    end
    request.content_type = 'application/json'
    request.body = body.to_json unless body.nil?
    Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) { |http| http.request(request) }
  end

  private

  def email_me_the_document(document)
    UserMailer.send_me_document(document).deliver_now!
    redirect_to documents_path, notice: I18n.t('EForm.Messages.Success.EmailSent')
  end

  def set_document
    @document = Document.find(params[:id])
  end

  def document_params
    params.require(:document).permit(:name, :user_id)
  end

  def pdf_params
    params.permit(:id, :format).to_h
  end

  def access_request_body
    {
      client_id: ENV['CLIENT_ID'],
      client_secret: ENV['CLIENT_SECRET'],
      grant_type: ENV['CLIENT_CREDENTIALS']
    }
  end

  def interview_request_body
    {
      templateId: '04d9d0ba-3113-40d3-9a4e-e7b226a72154',
      partyEmailAddress: current_user.email,
      partnerEndUserId: current_user.id
    }
  end
end
# rubocop:enable Metrics/ClassLength

app/helpers/documents_helper.rb
# frozen_string_literal: true

# rubocop:disable Style/Documentation

module DocumentsHelper
end

# rubocop:enable Style/Documentation

app/views/documents/_form.html.erb
<script src="https://logo-ipsum.sandbox.rocketlawyer.com/rocket-document.js"></script>
<rocket-document serviceToken="<%= @service_token %>" interviewId="<%= @interview_id %>"></rocket-document>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/generate_pdf.pdf.erb
<%= @document.name %>

app/views/documents/index.html.erb
<%= render 'layouts/breadcrumb_headings' %>

<%= link_to 'New Document', new_document_path, class: 'btn btn-primary-custom doc-btn pull-right' %>
<table class="table table-striped table-bordered">
  <thead>
  <tr>
    <th>Name</th>
    <th>Created At</th>
    <th class="dm_table_actions">Actions</th>
  </tr>
  </thead>
  <% @documents.each do |document| %>
    <% id = document.id %>
    <tbody>
    <tr>
      <td>
        <div class="dm_table_name document_name"><%= document.name %></div>
        <div class="display-none" id="DocumentNameField<%= id %>">
          <input
            type="text"
            name="document[name]"
            value="<%= document.name %>"
            data-id="<%= id %>"
            class="form-control"
            id="TextField<%= id %>"
          >
          <span><i class="fa icon_style" onclick="$(this).UpdateFromIcon(<%= id %>);">&#xf058;</i></span>
        </div>
        <div class="dm_table_source">
          Source:
          <a href="<%= documents_url %>"><%= document.name %></a>
        </div>
      </td>
      <td>
        <%= document.created_at.strftime('%d/%m/%Y') %>
      </td>
      <td class="doc-table-actions">
        <!-- Edit Button -->
        <!--        <a href="#" class="btn btn-primary-custom">-->
        <!--          <i class="fa fa-edit"></i> Edit </a>-->

        <!-- Export button -->
        <button
          type="button"
          class="btn btn-primary-custom"
          data-toggle="modal"
          data-target="#ExportModal<%= id %>"
        >
          <i class="fa fa-cloud-download"></i>
          Export
        </button>

        <!-- Action Button -->
        <div class="btn-group">
          <button type="button" name="dm_button_more" class="btn dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bars"></i> More
          </button>
          <ul class="dropdown-menu">
            <li>
              <a href="#">
                <i class="fa fa-edit"></i> Edit </a>
            </li>
            <li>
              <a role="button" id="EditDocument" onclick="$(this).ShowTextField(<%= id %>);">
                <i class="fa fa-tag"></i> Rename </a>
            </li>
            <li>
              <a
                rel="nofollow"
                data-method="delete"
                href="/documents/<%= id %>"
                data-confirm="Are you sure?"
              >
                <i class="fa fa-trash"></i> Delete </a>
            </li>
          </ul>
        </div>
      </td>
    </tr>

    <!-- Dynamic Modal -->
    <div
      class="modal fade"
      id="ExportModal<%= id %>"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalCenterTitle"
      aria-hidden="true"
    >
      <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <br>
            <div class="row">
              <div class="col-md-12">
                <div class="col-md-6">
                  <fieldset>
                    <div class="form-group">
                      <label>Choose name of the document</label>
                      <input type="text" class="form-control">
                    </div>
                  </fieldset>
                  <div class="dm_form_preview_title_text display-none"></div>
                </div>
                <div class="col-md-6 exports-buttons-margin">
                  <div class="pull-right">

                    <button
                      class="btn btn-primary-custom"
                      onclick="location.href='<%= export_document_path(id: id, from: 'print', format: :pdf) %>'"
                    >
                      <i class="fa fa-print"></i> <span>Print</span>
                    </button>

                    <button
                      class="btn btn-primary-custom"
                      onclick="location.href='<%= export_document_path(id: id, from: 'email') %>'"
                    >
                      <i class="fa fa-envelope-o"></i> <span>Email</span>
                    </button>

                    <div class="btn-group">
                      <button
                        class="btn btn-primary-custom"
                        onclick="location.href='<%= export_document_path(id: id, from: 'download', format: :pdf) %>'"
                      >
                        <i class="fa fa-download"></i> <span>Download</span>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>
          <div class="modal-body">
            <%= document.name %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </tbody>
</table>
<!--    TODO Add pagination-->

app/views/documents/new.html.erb
<%= render 'form', document: @document, interview_id: @interview_id, service_token: @service_token %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @document.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @document.user_id %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>