config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  devise_scope :user do
    get '/auth/google_oauth2/callback', to: 'sessions#google_auth'
  end
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :documents do
    member do
      get :export
      get :generate_pdf
    end
  end
  resources :subscriptions, only: %i[index update] do
    collection do
      get :plans
    end
  end
  resources :payments, only: :index
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  # Associations
  belongs_to :user
end

app/controllers/subscriptions_controller.rb
# frozen_string_literal: true

# This controller is responsible for manage subscription
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: %i[update plans]

  def index
    @subscription = current_user.subscription
    @countries = CS.countries.values.sort
  end

  def update
    if @subscription.update(subscription_params)
      redirect_to subscriptions_url, notice: 'Your details were successfully saved.'
    else
      redirect_to subscriptions_url, notice: 'Some went wrong please update again.'
    end
  end

  def plans; end

  private

  def set_subscription
    @subscription = Subscription.find(params[:id])
  end

  def subscription_params
    params.permit(:email, :first_name, :last_name, :company, :address_line_one, :address_line_two, :city,
                  :zip_code, :country, :state, :user_id)
  end
end

app/helpers/subscriptions_helper.rb
# frozen_string_literal: true

# rubocop:disable Style/Documentation

module SubscriptionsHelper
end
# rubocop:enable Style/Documentation

app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription) do |form| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
        <% subscription.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="field">
    <%= form.label :address_line_one %>
    <%= form.text_field :address_line_one %>
  </div>

  <div class="field">
    <%= form.label :address_line_two %>
    <%= form.text_field :address_line_two %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :zip_code %>
    <%= form.text_field :zip_code %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<%= render 'layouts/breadcrumb_headings' %>

<div class="row">

  <!-- Subscription form -->
  <div class="col-md-8">
    <div class="dm_settings_section">
      <div class="subscription-details">
        <% unless @subscription&.email.present? %>
          <p>
            You don't have active any subscription.</p>
        <% end %>
        <p>
          <a href="<%= plans_subscriptions_path(id: @subscription.id) %>" class="btn btn-primary-custom">Subscription
            Plans</a>
        </p>
      </div>
    </div>

    <!-- Start subscription form -->
    <div class="dm_settings_section_heading">
      <h3>Billing Details</h3>
    </div>


    <%= form_with(url: "/subscriptions/#{@subscription.id}", method: :put) do |f| %>
      <% f.hidden_field :user_id, value: current_user.id %>

      <!-- Email -->
      <fieldset>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email,
                           class: 'form-control',
                           placeholder: 'enter your email',
                           value: check_for(@subscription&.email)
          %>
        </div>
      </fieldset>

      <!-- First name -->
      <fieldset>
        <div class="row">
          <div class="col-md-6">
            <%= f.label :first_name %>
            <%= f.text_field :first_name,
                             class: 'form-control',
                             placeholder: 'enter your first name',
                             value: check_for(@subscription&.first_name)
            %>
          </div>
          <div class="col-md-6">
            <%= f.label :last_name %>
            <%= f.text_field :last_name,
                             class: 'form-control',
                             placeholder: 'enter your first name',
                             value: check_for(@subscription&.last_name)
            %>
          </div>
        </div>
      </fieldset>
      <br>

      <!-- Company -->
      <fieldset>
        <div class="form-group">
          <%= f.label :company %>
          <%= f.text_field :company,
                           class: 'form-control',
                           placeholder: '(optional)',
                           value: check_for(@subscription&.company)
          %>
        </div>
      </fieldset>

      <!-- Address line 1 -->
      <fieldset>
        <div class="form-group">
          <%= f.label 'Address Line 1' %>
          <%= f.text_field :address_line_one,
                           class: 'form-control',
                           placeholder: 'enter address line 1',
                           value: check_for(@subscription&.address_line_one)
          %>
        </div>
      </fieldset>

      <!-- Address line 2 -->
      <fieldset>
        <div class="form-group">
          <%= f.label 'Address Line 2' %>
          <%= f.text_field :address_line_two,
                           class: 'form-control',
                           placeholder: 'enter address line 2',
                           value: check_for(@subscription&.address_line_two)
          %>
        </div>
      </fieldset>

      <!-- City / Zip Code -->
      <fieldset>
        <div class="row">
          <div class="col-md-6">
            <%= f.label :city %>
            <%= f.text_field :city,
                             class: 'form-control',
                             placeholder: 'enter your city name',
                             value: check_for(@subscription&.city)
            %>
          </div>
          <div class="col-md-6">
            <%= f.label 'Zip Code' %>
            <%= f.text_field :zip_code,
                             class: 'form-control',
                             placeholder: 'enter your zip code',
                             value: check_for(@subscription&.zip_code)
            %>
          </div>
        </div>
      </fieldset>
      <br>

      <!-- Contry -->
      <fieldset>
        <div class="row">
          <div class="col-md-6">
            <%= f.label :country %>
            <%= f.select :country,
                         options_for_select(@countries,
                                            selected: check_for(@subscription&.country)
                         ),
                         {},
                         { class: 'form-control' }
            %>
          </div>
          <div class="col-md-6">
            <%= f.label 'Sate / Province' %>
            <%= f.text_field :state,
                             class: 'form-control',
                             placeholder: 'enter state',
                             value: check_for(@subscription&.state)
            %>
          </div>
        </div>
      </fieldset>
      <br>

      <%= f.submit 'Save', class: 'button right btn btn-primary-custom' %>
    <% end %>


  </div>


  <!-- Search documents -->
  <div class="col-md-4">
    <%= render 'layouts/side_widget' %>
  </div>
</div>

app/views/subscriptions/new.html.erb
<h1>New Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/plans.html.erb
<%= render 'layouts/breadcrumb_headings' %>

<div class="row">

  <!-- Subscription form -->
  <div class="col-md-8">

    <!-- Monthly plan card -->

    <div class="alert alert-dismissible alert-danger">
      <div id="flash_alert">
        <p>
          Your document was saved to you account. Try one of our subscriptions to print your document and access all
          features.
        </p>
      </div>
    </div>

    <div class="plan-heading subscription_highlight">
      <h2>Monthly Plan</h2>
      <div class="plan-description">
        <p></p>
        <ul>
          <li><strong>7-Day Free Trial</strong> - Unlimited access to all documents</li>
          <li><span style="background-color: initial; font-weight: inherit;">No commitment, cancel anytime</span></li>
          <li>After 7 days automatically renews at $39 / month</li>
        </ul>
        <p></p>
      </div>

      <div class="clearfix">
        <div class="plan-description-buttons">
          <button type="button" onclick="window.location.href='<%= payments_path(id: @subscription.id) %>'" class="btn btn-primary-custom">
            Select Plan <i class="fa fa-arrow-right icon-right"></i>
          </button>
        </div>

        <div class="plan-description-price">
          Free
        </div>
      </div>
    </div>

    <!-- Single document card -->
    <div class="plan-heading">
      <h2>Single Document</h2>
      <p>Alaska Eviction Notice (Notice to Quit) Form</p>
      <div class="plan-description">
        <p></p>
        <ul>
          <li><strong>One time purchase</strong>- just this document</li>
          <li>Unlimited access and revisions of one documents</li>
          <li>No commitment or monthly fees</li>
        </ul>
        <p></p>
      </div>

      <div class="clearfix">
        <div class="plan-description-buttons">
          <button type="button" onclick="window.location.href='<%= payments_path(id: @subscription.id) %>'" class="btn btn-primary-custom">
            Select Plan <i class="fa fa-arrow-right icon-right"></i>
          </button>
        </div>

        <div class="plan-description-price">
          $45 <span class="plan-description-price-after">/ single document</span>
        </div>
      </div>
    </div>
  </div>


  <!-- Search documents -->
  <div class="col-md-4">
    <%= render 'layouts/side_widget' %>
  </div>
</div>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @subscription.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @subscription.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @subscription.last_name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @subscription.company %>
</p>

<p>
  <strong>Address line one:</strong>
  <%= @subscription.address_line_one %>
</p>

<p>
  <strong>Address line two:</strong>
  <%= @subscription.address_line_two %>
</p>

<p>
  <strong>City:</strong>
  <%= @subscription.city %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @subscription.zip_code %>
</p>

<p>
  <strong>Country:</strong>
  <%= @subscription.country %>
</p>

<p>
  <strong>State:</strong>
  <%= @subscription.state %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>