config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  devise_scope :user do
    get '/auth/google_oauth2/callback', to: 'sessions#google_auth'
  end
  resources :users do
    member do
      get :confirm_email
    end
  end
  resources :documents do
    member do
      get :export
      get :generate_pdf
    end
  end
  resources :subscriptions, only: %i[index update] do
    collection do
      get :plans
    end
  end
  resources :payments, only: :index
end

app/views/layouts/_breadcrumb_headings.html.erb
<% if current_page?(root_path) %>
  <div class="col-lg-12 access-doc-breadcrumb-row">
    <span><a href="<%= check_for_home_path %>">Home</a></span>
    »
    <span class="access-doc-text">Access Your Documents</span>
  </div>
  <div class="col-md-12 access-doc-heading-row">
    <span class="access-doc-heading">Access Your Documents</span>
  </div>
<% elsif current_page?(documents_path) %>
  <div class="col-lg-12 access-doc-breadcrumb-row">
    <span><a href="<%= check_for_home_path %>">Home</a></span>
    »
    <span><a href="<%= documents_path %>">My eForms</a></span>
    »
    <span class="access-doc-text">My Documents</span>
  </div>
  <div class="col-md-12 access-doc-heading-row">
    <span class="access-doc-heading">My Documents</span>
  </div>
<% elsif current_page?(new_document_path) %>
  <div class="col-lg-12 access-doc-breadcrumb-row">
    <span><a href="<%= check_for_home_path %>">Home</a></span>
    »
    <span class="access-doc-text"><b>Florida Residential Lease Agreement</b></span>
  </div>
  <div class="col-md-12 access-doc-heading-row">
    <span class="access-doc-heading">Florida Residential Lease Agreement</span>
  </div>
<% elsif current_page?(new_user_password_path) || current_page?(edit_user_password_path) %>
  <div class="col-lg-12 access-doc-breadcrumb-row">
    <span>Home</span> » <span class="access-doc-text">Password Recovery</span>
  </div>
  <div class="col-md-12 access-doc-heading-row">
    <span class="access-doc-heading">Password Recovery</span>
  </div>
<% elsif current_page?(edit_user_registration_path) %>
  <div class="col-lg-12 access-doc-breadcrumb-row">
    <span><a href="<%= check_for_home_path %>">Home</a></span>
    »
    <span><a href="<%= documents_path %>">My eForms</a></span>
    »
    <span class="access-doc-text">Change Password</span>
  </div>
  <div class="col-md-12 access-doc-heading-row">
    <span class="access-doc-heading">Change Password</span>
  </div>
<% elsif current_page?(subscriptions_path) %>
  <div class="col-lg-12 access-doc-breadcrumb-row">
    <span><a href="<%= check_for_home_path %>">Home</a></span>
    »
    <span><a href="<%= documents_path %>">My eForms</a></span>
    »
    <span class="access-doc-text">Subscription</span>
    <div class="col-md-12 access-doc-heading-row">
      <span class="access-doc-heading">Subscription</span>
    </div>
  </div>
<% elsif current_page?(plans_subscriptions_path) || current_page?(payments_path) %>
  <div class="col-lg-12 access-doc-breadcrumb-row">
    <span><a href="<%= check_for_home_path %>">Home</a></span>
    »
    <span><a href="<%= documents_path %>">My eForms</a></span>
    »
    <span class="access-doc-text">Premium Plans</span>
    <div class="col-md-12 access-doc-heading-row">
      <span class="access-doc-heading">Premium Plans</span>
    </div>
  </div>
<% end %>

<hr class="horizontalLine">

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">

      <!-- Left 6 column -->
      <div class="col-md-3">
        <div class="footer-logo-list">

          <!-- Footer Logo -->
<!--          <div class="logo-footer"></div>-->

          <!-- Footer Links -->
          <div class="footer-ul-li">
            <ul>
              <li><a href="#">Contact</a></li>
              <li><a href="#">Pricing</a></li>
              <li><a href="#">FAQ (Frequently Asked Questions)</a></li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Right 6 column -->
      <div class="col-md-3 mobile-center">
        <div class="footer-rating-list">
          <!-- Ratting Bades -->
          <ul class="no_ul_appearance">
            <li id="custom_html-2" class="widget_text widget widget_custom_html">
              <div class="textwidget custom-html-widget">
                <!-- Begin widget code -->
                <div data-rw-badge1="19884">
                  <rw-widget-badge1 data-rw-badge1="19884" class="hydrated rw-badge fixed"></rw-widget-badge1>
                </div>
                <script>
                    var script = document.createElement("script");
                    script.type = "module";
                    script.src = "https://widgets.thereviewsplace.com/2.0/rw-widget-badge1.js";
                    document.getElementsByTagName("head")[0].appendChild(script);</script>
                <!-- End widget code -->
              </div>
            </li>
            <li id="custom_html-3" class="widget_text widget widget_custom_html">
              <div class="textwidget custom-html-widget">
                <!-- Begin widget code -->
                <div data-rw-badge1="19882">
                  <rw-widget-badge1 data-rw-badge1="19882" class="hydrated rw-badge fixed"></rw-widget-badge1>
                </div>
                <script>var script = document.createElement("script");
                script.type = "module";
                script.src = "https://widgets.thereviewsplace.com/2.0/rw-widget-badge1.js";
                document.getElementsByTagName("head")[0].appendChild(script);
                </script>
                <!-- End widget code -->
              </div>
            </li>
          </ul>
        </div>
      </div>

    </div>

  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-fixed-top nav-bg">
    <div class="container">

      <!-- Application Logo -->
      <!--      <div class="img">-->
      <!--        <a href="<%#= user_signed_in? ? e_forms_url : root_path %>">-->
      <!--          <img src="/eform_logo.png" class="pull-left">-->
      <!--        </a>-->
      <!--      </div>-->

      <!-- Header links -->
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">

          <!-- Common Links -->
          <li><a href="#" class="header-common-link"><b>Business</b></a></li>
          <li><a href="#" class="header-common-link"><b>Personal</b></a></li>
          <li><a href="#" class="header-common-link"><b>Real Estate</b></a></li>

          <!--Show links when user signed in-->
          <% if user_signed_in? %>
            <li>
              <div class="dropdown">

                <!-- My eForms parent link -->
                <button
                  onclick="location.href='<%= documents_path %>'"
                  class="dropbtn <%= 'active-link' if from_e_form_tab? %>">
                  My eForms
                </button>

                <!-- My eForms child link -->
                <div class="dropdown-content">
                  <a
                    onclick="location.href='<%= documents_path %>'"
                    class="<%= 'dropdown-active-link' if current_page?(documents_path) %>">
                    My Document
                  </a>
                  <a
                    onclick="location.href='<%= subscriptions_path %>'"
                    class="<%= 'dropdown-active-link' if current_page?(subscriptions_path) %>">
                    Subscription
                  </a>
                  <a
                    onclick="location.href='<%= edit_user_registration_path %>'"
                    class="<%= 'dropdown-active-link' if current_page?(edit_user_registration_path) %>">
                    Change Password
                  </a>
                  <a rel="nofollow" data-method="delete" href="/users/sign_out">Sign Out</a>
                </div>

              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_side_widget.html.erb
<div class="search-documents">
  <div class="row">
    <div class="col-md-12">

      <% if current_page?(edit_user_registration_path) || current_page?(subscriptions_url) %>
        <div id="sidebar" class="rounded">
          <ul>
            <li>
              <ul class="dm_navigation">
                <li>
                  <a
                    href="<%= documents_path %>"
                    class="<%= 'dropdown-active-link' if current_page?(documents_path) %>">
                    My Documents
                  </a>
                </li>
                <li>
                  <a
                    href="<%= subscriptions_path %>"
                    class="<%= 'dropdown-active-link' if current_page?(subscriptions_path) %>">
                    Subscription
                  </a>
                </li>
                <li>
                  <a
                    href="<%= edit_user_registration_path %>"
                    class="<%= 'dropdown-active-link' if current_page?(edit_user_registration_path) %>">
                    Change Password
                  </a>
                </li>
                <li>
                  <a
                    rel="nofollow"
                    data-method="delete"
                    href="/users/sign_out">
                    Sign Out
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </div>

        <div class="sign-in-widget">

          <!-- Help heading -->
          <div class="side-widget-element">
            <span class="heading">Do you need help?</span>
          </div>

          <!-- Help description -->
          <div class="side-widget-element">
            <span class="help-description">
              Our support agents are standing by to assist you. Please be aware that our agents are not licensed
              attorneys and cannot address legal questions.
            </span>
          </div>

          <!-- Phone -->
          <div class="side-widget-element">
            <div class="row">
              <div class="">
                <div class="col-md-1 fa-container"><i class="fa fa-phone font-awesome-size"></i></div>
                <div class="col-md-9">
                  <span><b>Phone</b></span><br>
                  <span>1 (844) 533-6767</span><br>
                  <span class="timing">(9am to 9am, sat/sun 9am to 5pm)</span>
                </div>
              </div>
            </div>
          </div>

          <!-- Chat -->
          <div class="row">
            <div class="contact-section">
              <div class="col-md-1 fa-container"><i class="fa fa-comments font-awesome-size"></i></div>
              <div class="col-md-9">
                <span><b>Chat</b></span><br>
                <span>Online - Start Chat</span><br>
              </div>
            </div>
          </div>

          <!-- Email -->
          <div class="row">
            <div class="contact-section">
              <div class="col-md-1 fa-container"><i class="fa fa-envelope font-awesome-size"></i></div>
              <div class="col-md-9 last-contact">
                <span><b>Email</b></span><br>
                <span>Send Message</span><br>
              </div>
            </div>
          </div>

        </div>

      <% elsif current_page?(root_path) || current_page?(new_user_password_path) || current_page?(edit_user_password_path) %>

        <div class="sign-in-widget">

          <!-- Search document heading -->
          <div class="side-widget-element">
            <span class="heading">Search Documents</span>
          </div>

          <!-- Search field -->
          <div class="side-widget-element">
            <form id="form">
              <input type="search" class="search-field" id="query" name="q" placeholder="Search..."/>
              <button type="submit" class="btn btn-primary-custom vertically-align">Search</button>
            </form>
          </div>

          <!-- Help heading -->
          <div class="side-widget-element">
            <span class="heading">Do you need help?</span>
          </div>

          <!-- Help description -->
          <div class="side-widget-element">
            <span class="help-description">
              Our support agents are standing by to assist you. Please be aware that our agents are not licensed
              attorneys and cannot address legal questions.
            </span>
          </div>

          <!-- Phone -->
          <div class="side-widget-element">
            <div class="row">
              <div class="">
                <div class="col-md-1 fa-container"><i class="fa fa-phone font-awesome-size"></i></div>
                <div class="col-md-9">
                  <span><b>Phone</b></span><br>
                  <span>1 (844) 533-6767</span><br>
                  <span class="timing">(9am to 9am, sat/sun 9am to 5pm)</span>
                </div>
              </div>
            </div>
          </div>

          <!-- Chat -->
          <div class="row">
            <div class="contact-section">
              <div class="col-md-1 fa-container"><i class="fa fa-comments font-awesome-size"></i></div>
              <div class="col-md-9">
                <span><b>Chat</b></span><br>
                <span>Online - Start Chat</span><br>
              </div>
            </div>
          </div>

          <!-- Email -->
          <div class="row">
            <div class="contact-section">
              <div class="col-md-1 fa-container"><i class="fa fa-envelope font-awesome-size"></i></div>
              <div class="col-md-9 last-contact">
                <span><b>Email</b></span><br>
                <span>Send Message</span><br>
              </div>
            </div>
          </div>

        </div>

      <% elsif params[:controller] == 'subscriptions' && params[:action] == 'plans' %>

        <div class="sign-in-widget">

          <!-- Features -->
          <div class="side-widget-element">
            <span class="heading">Features</span>
          </div>

          <!-- Subscription features -->
          <div class="side-widget-element">

            <!-- Encrypt -->
            <div class="membership-feature margin-top-10">
              <div class="membership-feature-icon"><i class="fa fa-lock"></i></div>
              Encrypted and Secure
            </div>

            <!-- Print -->
            <div class="membership-feature">
              <div class="membership-feature-icon"><i class="fa fa-print"></i></div>
              Print Unlimited Documents
            </div>

            <!-- cloud download -->
            <div class="membership-feature">
              <div class="membership-feature-icon"><i class="fa fa-cloud-download"></i></div>
              Export to PDF, Word and ODT
            </div>

            <!-- refresh -->
            <div class="membership-feature">
              <div class="membership-feature-icon"><i class="fa fa-refresh"></i></div>
              Regularly Updated
            </div>

            <!-- legal -->
            <div class="membership-feature">
              <div class="membership-feature-icon"><i class="fa fa-gavel"></i></div>
              Suited to your State Laws
            </div>

            <!-- diamond -->
            <div class="membership-feature">
              <div class="membership-feature-icon"><i class="fa fa-diamond"></i></div>
              100% Satisfaction Guarantee
            </div>

          </div>

          <!-- Help heading -->
          <div class="side-widget-element">
            <span class="heading">Do you need help?</span>
          </div>

          <!-- Help description -->
          <div class="side-widget-element">
            <span class="help-description">
              Our support agents are standing by to assist you. Please be aware that our agents are not licensed
              attorneys and cannot address legal questions.
            </span>
          </div>

          <!-- Phone -->
          <div class="side-widget-element">
            <div class="row">
              <div class="">
                <div class="col-md-1 fa-container"><i class="fa fa-phone font-awesome-size"></i></div>
                <div class="col-md-9">
                  <span><b>Phone</b></span><br>
                  <span>1 (844) 533-6767</span><br>
                  <span class="timing">(9am to 9am, sat/sun 9am to 5pm)</span>
                </div>
              </div>
            </div>
          </div>

          <!-- Chat -->
          <div class="row">
            <div class="contact-section">
              <div class="col-md-1 fa-container"><i class="fa fa-comments font-awesome-size"></i></div>
              <div class="col-md-9">
                <span><b>Chat</b></span><br>
                <span>Online - Start Chat</span><br>
              </div>
            </div>
          </div>

          <!-- Email -->
          <div class="row">
            <div class="contact-section">
              <div class="col-md-1 fa-container"><i class="fa fa-envelope font-awesome-size"></i></div>
              <div class="col-md-9 last-contact">
                <span><b>Email</b></span><br>
                <span>Send Message</span><br>
              </div>
            </div>
          </div>

        </div>

      <% elsif params[:controller] == 'payments' && params[:action] == 'index' %>


        <div class="sign-in-widget">

          <!-- Order heading -->
          <div class="side-widget-element">
            <span class="heading">Your Order</span>
          </div>


          <!-- Order heading -->
          <div class="side-widget-element">

              <div class="dm_order_name">Monthly Plan</div>
              <div class="dm_order_value">$0.00</div>
              <br>
              <hr>
              <div class="dm_order_name"><b>Total</b></div>
              <div class="dm_order_value"><b>$0.00</b></div>
              <br>

              <div class="dm_order_description">
                Your trial subscription plan is free for 7 days and you can cancel anytime. After that you will pay just
                $39 per month starting on 29th January 2022 (EST).
                If you have any questions, please do not hesitate and use our support via phone, online chat or email.
              </div>
          </div>


          <!-- Help heading -->
          <div class="side-widget-element">
            <span class="heading">Do you need help?</span>
          </div>

          <!-- Help description -->
          <div class="side-widget-element">
            <span class="help-description">
              Our support agents are standing by to assist you. Please be aware that our agents are not licensed
              attorneys and cannot address legal questions.
            </span>
          </div>

          <!-- Phone -->
          <div class="side-widget-element">
            <div class="row">
              <div class="">
                <div class="col-md-1 fa-container"><i class="fa fa-phone font-awesome-size"></i></div>
                <div class="col-md-9">
                  <span><b>Phone</b></span><br>
                  <span>1 (844) 533-6767</span><br>
                  <span class="timing">(9am to 9am, sat/sun 9am to 5pm)</span>
                </div>
              </div>
            </div>
          </div>

          <!-- Chat -->
          <div class="row">
            <div class="contact-section">
              <div class="col-md-1 fa-container"><i class="fa fa-comments font-awesome-size"></i></div>
              <div class="col-md-9">
                <span><b>Chat</b></span><br>
                <span>Online - Start Chat</span><br>
              </div>
            </div>
          </div>

          <!-- Email -->
          <div class="row">
            <div class="contact-section">
              <div class="col-md-1 fa-container"><i class="fa fa-envelope font-awesome-size"></i></div>
              <div class="col-md-9 last-contact">
                <span><b>Email</b></span><br>
                <span>Send Message</span><br>
              </div>
            </div>
          </div>

        </div>

      <% else %>


      <% end %>


      <!-- Chat / Email -->
      <% unless params[:controller] == 'subscriptions' && params[:action] == 'plans' %>

      <% end %>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <!--  Fontawesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- Meta tags -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "iPM App" %>">
  <%= csrf_meta_tags %>

  <!-- Application title -->
  <title><%= content_for?(:title) ? yield(:title) : "iPM App" %></title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</head>

<!-- Application Body -->
<body>
<div class="container">
  <%= render 'layouts/header' %>
  <div class="main-div">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
</div>
<!--Footer-->
<%= render 'layouts/footer' unless params[:controller] == 'documents' && params[:action] == 'new' %>
</body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
  <meta charset="utf-8"/>
  <%= wicked_pdf_stylesheet_link_tag "pdf" %>
</head>
<body onload="number_pages">
<div id="header">
  <!--= wicked_pdf_image_tag 'thumbnail.png', height: "30", width: "auto"
  -->
</div>
<div id="content">
  <%= yield %>
</div>
</body>
</html>